### ISSUE TITLE
Please add metal (MSL) support

### ISSUE THREAD

**Issue by kov** [GPUOpen-Effects/FidelityFX#8]
On Macs metal is the only API supported by many games now, and it would be great to be able to use these technologies on games such as World of Warcraft running on Macs.

**Comment by rys** [comment]
We're currently focused on Windows PC and Xbox with our FidelityFX work, but we're very happy for others to take FidelityFX technology and make it available on any platform they'd like. We specifically license everything as MIT to encourage that, so that it can happen outside of the platforms we're focused on ourselves, as Valve did recently for DOTA2.

As a Mac user myself outside of work, I'm very keen to see it happen, so if anyone takes on a port to Metal for any FidelityFX effect we're happy to answer questions and assist where we can.
